version: '3.8'
services:
  db:
    image: mariadb:10
    container_name: wordpress-db
    restart: unless-stopped
    env_file: .env
    environment: 
      - MYSQL_DATABASE=wordpress
    # ports: 
    #   - 3306:3306
    volumes: 
      - ./db:/var/lib/mysql
      # - ./.config/fixtures:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'
    networks: 
      - wordpress-network

  adminer:
    image: adminer:latest
    container_name: wordpress-adminer
    restart: unless-stopped
    environment: 
      - ADMINER_DEFAULT_SERVER=db
    ports: 
      - 8080:8080
    networks: 
      - wordpress-network
    links: 
      - db:db

  wordpress:
    depends_on: 
      - db
    image: wordpress:fpm-alpine
    container_name: wordpress-wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./app:/var/www/html
    networks: 
      - wordpress-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21-alpine
    container_name: wordpress-webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./.config:/etc/nginx/conf.d
      # - ./ssl:/etc/letsencrypt
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
